version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: oauth_app_development
      POSTGRES_USER: oauth_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5435:5432" # Cambia 5435 al puerto que desees usar en tu host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
