default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: oauth_user
  password: securepassword
  host: localhost
  port: 5435

development:
  <<: *default
  database: oauth_app_development

test:
  <<: *default
  database: oauth_app_test

production:
  <<: *default
  database: oauth_app_production
  username: oauth_app
  password: <%= ENV["OAUTH_APP_DATABASE_PASSWORD"] %>
